

console_command = "/code/manage.py createsuperuser --username admin --email admin@exemplo.com --noinput && python manage.py shell -c "from django.contrib.auth import get_user_model; User = get_user_model(); u = User.objects.get(username='admin'); u.set_password('123456789');Â u.save()"
